language: android
dist: trusty

env:
  global:
    - ADB_INSTALL_TIMEOUT=15

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-google_apis-25

before_script:
  - echo no | android create avd --force -n test -t android-26 --abi google_apis/armeabi-v7a -c 32M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 180
  - adb devices
  - adb shell input keyevent 82 &

script:
   - ./gradlew build connectedCheck -PdisablePreDex
