language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=default/x86

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-x86-android-23
script:
  - android list targets
  - echo no | android create avd --force -n test -t android-23 --abi default/x86
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedAndroidTest
