language: android

before_install:
  - set -e
  - git fetch --unshallow
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - chmod +x ${NVM_DIR}/nvm.sh
  - ${NVM_DIR}/nvm.sh
  - nvm install v8
  - npm install --save-dev @commitlint/{config-conventional,cli}
  - chmod +x lint-commits.sh

script:
  - set -e
  - ./lint-commits.sh

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
